Solution/InterviewTestTemplatev2/ViewModels/BonusCalculator.cs
using InterviewTestTemplatev2.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace InterviewTestTemplatev2.ViewModels
{
    public class BonusCalculatorInput
    {
        [Required(ErrorMessage = "{0} is mandatory.")]
        [Display(Name = "Pool amount")]
        [PositiveNumber]
        public int BonusPoolAmount { get; set; }

        [Display(Name = "Employee name")]
        public IEnumerable<HrEmployee> AllEmployees { get; set; }
        public int SelectedEmployeeId { get; set; }
    }

    public class BonusCalculatorResult
    {

        public decimal bonusPoolAllocation;

        public HrEmployee hrEmployee;
    }
}

Solution/InterviewTestTemplatev2/Controllers/BonusCalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using InterviewTestTemplatev2.Data;
using InterviewTestTemplatev2.ViewModels;


namespace InterviewTestTemplatev2.Controllers
{
    public class BonusCalculatorController : Controller
    {
        public MvcInterviewV3Entities1 db = new MvcInterviewV3Entities1();

        // GET: BonusPool
        public ActionResult Input()
        {
            var viewModel = new BonusCalculatorInput
            {
                AllEmployees = HrEmployee.GetEmployeeList()
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Calculate(BonusCalculatorInput model)
        {
            if (ModelState.IsValid)
            {
                int selectedEmployeeId = model.SelectedEmployeeId;
                int totalBonusPool = model.BonusPoolAmount;

                var selectedEmployee = HrEmployee.FindById(selectedEmployeeId);
                var bonusAllocation = HrEmployee.CalculateBonus(model.SelectedEmployeeId, model.BonusPoolAmount);

                var viewModel = new BonusCalculatorResult
                {
                    hrEmployee = selectedEmployee,
                    bonusPoolAllocation = bonusAllocation
                };

                return View("Result", viewModel);
            }
            else
            {
                model.AllEmployees = HrEmployee.GetEmployeeList();
                return View("Input", model);

            }
        }
    }
}

Solution/InterviewTestTemplatev2/Views/BonusCalculator/Input.cshtml
@model InterviewTestTemplatev2.ViewModels.BonusCalculatorInput

@{
    ViewBag.Title = "Index";
}

<h2>Bonus Pool Calculator</h2>

<p>
    In order to calculate the bonus pool allocation for a particular employee, please:
    <br />
    <br />
    1. Enter in a valid amount for the total bonus pool<br />
    2. Select an employee for whom you wish to calculate the allocation<br />
    
</p>

@using (Html.BeginForm("Calculate", "BonusCalculator", FormMethod.Post))
{

@Html.AntiForgeryToken()
<div>
    <div class="form-body">
        <div class="form-group">
            <label>Bonus Pool Amount (£):</label>
            <div class="group-control">@Html.EditorFor(model => model.BonusPoolAmount) @Html.ValidationMessageFor(model => model.BonusPoolAmount)</div>
        </div>
    </div>
    <div class="form-group">
        <label>Employee:</label>
        <div class="group-control">@Html.DropDownListFor(model => model.SelectedEmployeeId, new SelectList(Model.AllEmployees, "ID", "Full_Name"))</div>
    </div>
    <div class="buttons-row">
        <div class="buttons"></div>
            <input type="submit" value="Calculate" />
    </div>

 </div>

        }

Solution/InterviewTestTemplatev2/Views/BonusCalculator/Result.cshtml
@using InterviewTestTemplatev2.ViewModels;
@using InterviewTestTemplatev2.Controllers;

@model BonusCalculatorResult


@{
    ViewBag.Title = "Caclulate";
}

<h2>Bonus Pool Allocation</h2>

<p>The bonus pool allocation for @Html.DisplayFor(model => model.hrEmployee.Full_Name) is: £@Html.DisplayFor(model => model.bonusPoolAllocation)</p>

@Html.ActionLink("Click here to calculate for another employee", nameof(BonusCalculatorController.Input))

Solution/InterviewTestTemplatev2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel='stylesheet' href="/styles/FrontEnd.css" type='text/css' />
    <!--[if lt IE 11]> <script src='https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js'></script> <![endif]-->
</head>
<body>
    <div class="side-bar nav navbar-nav">
        <div class="logo">
            <img src="~/Public/logo.png" />
        </div>
        <div class="navbar-header">

            @Html.ActionLink("Bonus Pool Calculator", "Index", "BonusPool", new { area = "" }, new { @class = "navbar-brand" })

        </div>
        <footer>
            <p>&copy; @DateTime.Now.Year - Ally.yousefi@gmail.com</p>
        </footer>
    </div>
    <div class="body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>